"""
SAFER Data Service — ORM Models

SQLAlchemy models for transactions, audit logs, and alerts.
Schema mirrors the CSV dataset structure + ML scoring outputs.
"""

from datetime import datetime, timezone
from sqlalchemy import (
    Column, String, Integer, Float, Boolean, DateTime, Text,
    ForeignKey, Index,
)
from data_service.database import Base


def _utcnow():
    return datetime.now(timezone.utc)


class Transaction(Base):
    """Core transaction record — raw data + ML scoring + audit state."""

    __tablename__ = "transactions"

    id = Column(String(20), primary_key=True)
    timestamp = Column(DateTime, nullable=False, index=True)

    # Sender
    sender_name = Column(String(100))
    sender_account = Column(String(20))
    sender_bank = Column(String(20))
    sender_city = Column(String(50))
    sender_province = Column(String(50))
    sender_lat = Column(Float)
    sender_lng = Column(Float)

    # Receiver
    receiver_name = Column(String(100))
    receiver_account = Column(String(20))
    receiver_bank = Column(String(20))
    receiver_city = Column(String(50))
    receiver_province = Column(String(50))
    receiver_lat = Column(Float)
    receiver_lng = Column(Float)

    # Transaction details
    amount = Column(Float, nullable=False)
    payment_rail = Column(String(30), nullable=False)
    ewallet_provider = Column(String(20), default="None")
    merchant = Column(String(100))
    merchant_category = Column(String(30))
    channel = Column(String(30))

    # Device & Network
    device_type = Column(String(30))
    device_brand = Column(String(50))
    device_fingerprint = Column(String(40))
    ip_address = Column(String(20))
    is_new_device = Column(Boolean, default=False)

    # Account metadata
    account_age_days = Column(Integer, default=365)

    # Fraud indicators (binary features — same as training data)
    is_velocity_anomaly = Column(Boolean, default=False)
    is_geo_mismatch = Column(Boolean, default=False)
    is_off_hours = Column(Boolean, default=False)
    is_high_value_for_rail = Column(Boolean, default=False)
    is_suspicious_ip = Column(Boolean, default=False)
    is_risky_merchant = Column(Boolean, default=False)
    is_new_account = Column(Boolean, default=False)
    has_failed_attempts = Column(Boolean, default=False)
    is_device_mismatch = Column(Boolean, default=False)
    is_sim_swap = Column(Boolean, default=False)
    is_unusual_beneficiary = Column(Boolean, default=False)
    velocity_count = Column(Integer, default=1)
    geo_distance_km = Column(Float, default=0.0)

    # ML Scoring results
    risk_score = Column(Integer, default=0)
    severity = Column(String(10), default="low", index=True)
    fraud_probability = Column(Float, default=0.0)
    xgb_probability = Column(Float, default=0.0)
    lgb_probability = Column(Float, default=0.0)

    # AI Reasoning (SHAP-based)
    ai_reasoning = Column(Text, default="")
    shap_values = Column(Text, default="")       # JSON blob
    primary_risk_factors = Column(Text, default="")  # JSON array
    suggested_action = Column(String(200), default="")

    # Audit workflow
    audit_status = Column(String(30), default="pending_review", index=True)
    audit_notes = Column(Text, default="")
    audited_by = Column(String(100))
    audited_at = Column(DateTime)

    # Metadata
    created_at = Column(DateTime, default=_utcnow)
    model_version = Column(String(10), default="v1")
    is_fraud = Column(Boolean, default=False)  # Ground truth label (if known)

    __table_args__ = (
        Index("ix_tx_severity_audit", "severity", "audit_status"),
        Index("ix_tx_rail", "payment_rail"),
    )


class AuditLog(Base):
    """Tracks every audit status change for compliance trail."""

    __tablename__ = "audit_logs"

    id = Column(Integer, primary_key=True, autoincrement=True)
    transaction_id = Column(
        String(20), ForeignKey("transactions.id"), nullable=False, index=True
    )
    from_status = Column(String(30))
    to_status = Column(String(30))
    changed_by = Column(String(100), default="Analyst Demo")
    notes = Column(Text, default="")
    created_at = Column(DateTime, default=_utcnow)


class Alert(Base):
    """Fraud alerts generated by the system."""

    __tablename__ = "alerts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    transaction_id = Column(
        String(20), ForeignKey("transactions.id"), nullable=False, index=True
    )
    alert_type = Column(String(30))  # high_risk, mule_ring, device_farm
    severity = Column(String(10))
    message = Column(Text, default="")
    is_resolved = Column(Boolean, default=False)
    created_at = Column(DateTime, default=_utcnow)
